enum ROUTES {
  // ---- Stacks
  ONBOARDING_STACK = "ONBOARDING_STACK",
  BOTTOM_TAB_STACK = "BOTTOM_TAB_STACK",

  // ----- Onboarding Screens -----
  SPLASH = "SPLASH",

  // ----- Dashboard Tabs -----
  COMMON_STACK = "COMMON_STACK",

  HOME_STACK = "HOME_STACK",
  AGENTS = "AGENTS",
  AGENT_HOME = "AGENT_HOME",
  AGENT_CHAT = "AGENT_CHAT",

  CATEGORIES_STACK = "CATEGORIES_STACK",
  CATEGORIES = "CATEGORIES",

  HISTORY_STACK = "HISTORY_STACK",
  HISTORY = "HISTORY",

  PROFILE_STACK = "PROFILE_STACK",
  PROFILE = "PROFILE",
}

export default ROUTES;
